services:
  # Xiaomi Speaker
  speaker:
    image: palemoky/xiaomi-speaker:latest
    container_name: speaker
    restart: unless-stopped
    network_mode: host
    env_file: .env
    security_opt: [no-new-privileges:true]
    cap_drop: [ALL]
    volumes:
      - speaker_data:/app/data # Persist Xiaomi account token
      - speaker_data:/app/audio_cache
      - speaker_data:/home/nonroot/.local/share/piper-voices
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Cloudflare Tunnel
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    restart: unless-stopped
    network_mode: host
    env_file: .env
    command: tunnel --no-autoupdate run
    security_opt: [no-new-privileges:true]
    cap_drop: [ALL]
    depends_on:
      speaker:
        condition: service_healthy

volumes:
  speaker_data:
