services:
  # Xiaomi Speaker
  speaker:
    image: palemoky/xiaomi-speaker:latest
    container_name: speaker
    restart: unless-stopped
    network_mode: host
    env_file: .env
    volumes:
      - type: volume
        source: speaker-data
        target: /app/audio_cache
        volume:
          subpath: audio_cache
      - type: volume
        source: speaker-data
        target: /app/logs
        volume:
          subpath: logs
      - type: volume
        source: speaker-data
        target: /root/.local/share/piper-voices
        volume:
          subpath: piper-voices
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Cloudflare Tunnel
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    restart: unless-stopped
    network_mode: host
    env_file: .env
    command: tunnel --no-autoupdate run
    depends_on:
      speaker:
        condition: service_healthy

volumes:
  speaker-data:
