version: '3.8'

# Xiaomi Speaker
services:
  speaker:
    image: palemoky/xiaomi-speaker:latest
    container_name: speaker
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./audio_cache:/app/audio_cache
      - ./logs:/app/logs
      - piper-voices:/root/.local/share/piper-voices
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Cloudflare Tunnel
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    command: tunnel --no-autoupdate run
    depends_on:
      speaker:
        condition: service_healthy

# 定义命名卷
volumes:
  piper-voices:
